# Generated by Django 6.0.1 on 2026-01-13 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("MBP", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rolemodelpermission",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MBP.appmodel"
            ),
        ),
        migrations.AddField(
            model_name="rolemodelpermission",
            name="permission_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MBP.permissiontype"
            ),
        ),
        migrations.AddField(
            model_name="rolemodelpermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MBP.role"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolemodelpermission",
            unique_together={("role", "model", "permission_type")},
        ),
    ]
